<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <PublishSingleFile Condition="'$(PublishSingleFile)' == ''">true</PublishSingleFile>
    <SelfContained Condition="'$(SelfContained)' == ''">false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controls\SkiaInkCanvas.cs" />
    <Page Remove="App.xaml" />
    <Page Remove="Pages\AnnotatePage.xaml" />
    <Compile Remove="Pages\AnnotatePage.xaml.cs" />
    <Page Remove="MainWindow.xaml" />
    <Compile Remove="MainWindow.xaml.cs" />
    <Page Remove="Windows\AnnotationOverlayWindow.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jalium.UI.Desktop" Version="26.10.3" />
    <PackageReference Include="Microsoft.Office.Interop.PowerPoint" Version="15.0.4420.1018" />
    <PackageReference Include="System.ObjectModel" Version="4.3.0" />
  </ItemGroup>

</Project>
