<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
        <NoWarn>NU1701</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MaterialDesignColors" Version="5.2.2-ci998" />
      <PackageReference Include="MaterialDesignThemes" Version="5.2.2-ci998" />
      <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
      <PackageReference Include="SkiaSharp" Version="3.119.0" />
      <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.0" />
    </ItemGroup>

</Project>
